/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'rafae' at '9/12/16 13:07' with Gradle 3.2.1
 *
 * @author rafae, @date 9/12/16 13:07
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
