import org.junit.Test;
import static org.junit.Assert.*;

/*
 * This Java source file was auto generated by running 'gradle init --type java-library'
 * by 'rafae' at '9/12/16 13:07' with Gradle 3.2.1
 *
 * @author rafae, @date 9/12/16 13:07
 */
public class LibraryTest {
    @Test public void testSomeLibraryMethod() {
        Library classUnderTest = new Library();
        assertTrue("someLibraryMethod should return 'true'", classUnderTest.someLibraryMethod());
		System.out.println("Ejecución de test");
    }
}
